apiVersion: v1
kind: Service
metadata:
  namespace: web-shop
  name: order-database-service
  labels:
    app: order-database-service
spec:
  ports:
    - name: "http"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: order-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-shop
  name: order-database
  labels:
    app: order-database
spec:
  selector:
    matchLabels:
      app: order-database
  template:
    metadata:
      labels:
        app: order-database
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-database-secret
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
      volumes:
        - name: mysql-initdb
          configMap:
            name: order-database-mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: web-shop
  name: order-database-mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE orders;
