kind: Service
apiVersion: v1
metadata:
  namespace: web-shop
  name: order-app-service
spec:
  selector:
    app: order-app
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: web-shop
  name: order-app-config
  labels:
    app: order-app
data:
  application.properties: |
    order.communication.endpoints.user=http://user-app-service.web-shop.svc.cluster.local:8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-shop
  name: order-app
  labels:
    app: order-app
spec:
  selector:
    matchLabels:
      app: order-app
  replicas: 1
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app
          image: joranbergfeld/order-app:v2
          ports:
            - containerPort: 8003
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-database-secret
                  key: password
