spring:
  application:
    name: payment-service

  jpa:
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/payments?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

server:
  port: 8002

