spring:
  jpa:
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8001
