spring:
  application:
    name: order-service
  jpa:
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/orders?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

server:
  port: 8000
order.communication.endpoints:
  user: http://localhost:8001
  payment: http://localhost:8002
  product: http://localhost:8003
  stock: http://localhost:8004
