spring:
  datasource:
    url: jdbc:mysql://order-database-service.web-shop.svc.cluster.local:3306/orders

order.communication.endpoints:
  user: http://user-app-service.web-shop.svc.cluster.local:8001
  payment: http://payment-app-service.web-shop.svc.cluster.local:8002
  product: http://product-app-service.web-shop.svc.cluster.local:8003
  stock: http://stock-app-service.web-shop.svc.cluster.local:8004
